[28/05/2022 03:25:18 AM] root INFO : HUAWEI
[28/05/2022 03:25:18 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[28/05/2022 03:25:24 AM] root INFO : HUAWEI
[28/05/2022 03:25:24 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[28/05/2022 03:25:25 AM] root INFO : ZTE C300
[28/05/2022 03:25:25 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[28/05/2022 03:25:27 AM] root INFO : ZTE C300
[28/05/2022 03:25:27 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[28/05/2022 03:25:27 AM] root ERROR : (1062, "Duplicate entry 'Evento24' for key 'name'")
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/APINetPix.py", line 23, in takePicGpon
    self.pic.id = self.insertPic()
  File "/home/desarrollo/NetPics/APINetPix.py", line 54, in insertPic
    idPic = self.db.insertPic(self.pic.name)
  File "/home/desarrollo/NetPics/NetPixDB.py", line 34, in insertPic
    cur.execute("INSERT INTO `net_pics`.`pics` (`name`, `date_time`) VALUES ('{}', '{}');".format(picName,datetime.today()))
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'Evento24' for key 'name'")
[28/05/2022 03:27:53 AM] root INFO : HUAWEI
[28/05/2022 03:27:53 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[28/05/2022 03:27:59 AM] root INFO : HUAWEI
[28/05/2022 03:27:59 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[28/05/2022 03:28:00 AM] root INFO : ZTE C300
[28/05/2022 03:28:00 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[28/05/2022 03:28:02 AM] root INFO : ZTE C300
[28/05/2022 03:28:02 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[30/05/2022 04:59:52 PM] root INFO : HUAWEI
[30/05/2022 04:59:52 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386688', 'value': '##OLT2-Cordoba_Mza_04/04/045-Illia_445_(2)_Resi_gpon0/10/3##'}
[30/05/2022 04:59:58 PM] root INFO : HUAWEI
[30/05/2022 04:59:58 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386688', 'value': '##OLT2-Cordoba_Mza_04/04/045-Illia_445_(2)_Resi_gpon0/10/3##'}
[30/05/2022 04:59:58 PM] root INFO : ZTE C300
[30/05/2022 04:59:59 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278723', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo666-gpon-olt_1/2/3##'}
[30/05/2022 05:00:01 PM] root INFO : ZTE C300
[30/05/2022 05:00:01 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278723', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo666-gpon-olt_1/2/3##'}
[31/05/2022 10:51:28 AM] root INFO : HUAWEI
[31/05/2022 10:51:29 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386944', 'value': '##OLT2-Cordoba_Mza_04/05/007-Caseros_690_(2)_Resi_gpon0/10/4##'}
[31/05/2022 10:51:35 AM] root INFO : HUAWEI
[31/05/2022 10:51:35 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386944', 'value': '##OLT2-Cordoba_Mza_04/05/007-Caseros_690_(2)_Resi_gpon0/10/4##'}
[31/05/2022 10:51:35 AM] root INFO : ZTE C300
[31/05/2022 10:51:35 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278724', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo748-gpon-olt_1/2/4##'}
[31/05/2022 10:51:37 AM] root INFO : ZTE C300
[31/05/2022 10:51:38 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278724', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo748-gpon-olt_1/2/4##'}
[31/05/2022 11:56:02 AM] root ERROR : 'main' object has no attribute 'db'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 38, in getOnusFromPic
    data = self.db.selectOnusInfoFromPic(picId)
AttributeError: 'main' object has no attribute 'db'
[31/05/2022 11:56:11 AM] root ERROR : 'main' object has no attribute 'db'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 38, in getOnusFromPic
    data = self.db.selectOnusInfoFromPic(picId)
AttributeError: 'main' object has no attribute 'db'
[31/05/2022 11:56:17 AM] root ERROR : 'main' object has no attribute 'db'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 38, in getOnusFromPic
    data = self.db.selectOnusInfoFromPic(picId)
AttributeError: 'main' object has no attribute 'db'
[31/05/2022 11:57:27 AM] root INFO : HUAWEI
[31/05/2022 11:57:28 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386944', 'value': '##OLT2-Cordoba_Mza_04/05/007-Caseros_690_(2)_Resi_gpon0/10/4##'}
[31/05/2022 12:24:17 PM] root INFO : HUAWEI
[31/05/2022 12:24:18 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386944', 'value': '##OLT2-Cordoba_Mza_04/05/007-Caseros_690_(2)_Resi_gpon0/10/4##'}
[31/05/2022 12:24:24 PM] root INFO : HUAWEI
[31/05/2022 12:24:24 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386944', 'value': '##OLT2-Cordoba_Mza_04/05/007-Caseros_690_(2)_Resi_gpon0/10/4##'}
[31/05/2022 12:24:24 PM] root INFO : ZTE C300
[31/05/2022 12:24:25 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278724', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo748-gpon-olt_1/2/4##'}
[31/05/2022 12:24:27 PM] root INFO : ZTE C300
[31/05/2022 12:24:27 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278724', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo748-gpon-olt_1/2/4##'}
[31/05/2022 12:24:36 PM] root ERROR : 'main' object has no attribute 'db'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 38, in getOnusFromPic
    data = self.db.selectOnusInfoFromPic(picId)
AttributeError: 'main' object has no attribute 'db'
[31/05/2022 12:24:44 PM] root ERROR : 'main' object has no attribute 'db'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 38, in getOnusFromPic
    data = self.db.selectOnusInfoFromPic(picId)
AttributeError: 'main' object has no attribute 'db'
[31/05/2022 12:29:32 PM] root ERROR : 'main' object has no attribute 'db'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 38, in getOnusFromPic
    data = self.db.selectOnusInfoFromPic(picId)
AttributeError: 'main' object has no attribute 'db'
[31/05/2022 10:53:55 PM] root ERROR : selectPicById() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 48, in getPic
    data = self.db.selectPicById(picId)
TypeError: selectPicById() takes 1 positional argument but 2 were given
[31/05/2022 10:55:02 PM] root ERROR : selectPicById() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 48, in getPic
    data = self.db.selectPicById(picId)
TypeError: selectPicById() takes 1 positional argument but 2 were given
[31/05/2022 11:29:45 PM] root ERROR : 'OltInfo' object has no attribute 'ip'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 59, in getPic
    oltInfo = OltInfo()
  File "/home/desarrollo/NetPics/OltInfo.py", line 19, in __init__
    Ip: {self.ip}
AttributeError: 'OltInfo' object has no attribute 'ip'
[31/05/2022 11:34:21 PM] root ERROR : 'OltInfo' object has no attribute 'ip'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 59, in getPic
    oltInfo = OltInfo()
  File "/home/desarrollo/NetPics/OltInfo.py", line 19, in __init__
    Ip: {self.ip}
AttributeError: 'OltInfo' object has no attribute 'ip'
[31/05/2022 11:35:00 PM] root ERROR : 'OltInfo' object has no attribute 'ip'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 59, in getPic
    oltInfo = OltInfo()
  File "/home/desarrollo/NetPics/OltInfo.py", line 19, in __init__
    Ip: {self.ip}
AttributeError: 'OltInfo' object has no attribute 'ip'
[31/05/2022 11:37:28 PM] root ERROR : 'OltInfo' object has no attribute 'ip'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 59, in getPic
    oltInfo = OltInfo()
  File "/home/desarrollo/NetPics/OltInfo.py", line 25, in __init__
    Ip: {self.ip}
AttributeError: 'OltInfo' object has no attribute 'ip'
[31/05/2022 11:38:10 PM] root ERROR : 'OltInfo' object has no attribute 'ip'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 59, in getPic
    oltInfo = OltInfo()
  File "/home/desarrollo/NetPics/OltInfo.py", line 25, in __init__
    Ip: {self.ip}
AttributeError: 'OltInfo' object has no attribute 'ip'
[31/05/2022 11:39:51 PM] root ERROR : 'OltInfo' object has no attribute 'ip'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 59, in getPic
    oltInfo = OltInfo()
  File "/home/desarrollo/NetPics/OltInfo.py", line 25, in __init__
    Ip: {self.ip}
AttributeError: 'OltInfo' object has no attribute 'ip'
[31/05/2022 11:40:55 PM] root ERROR : 'OltInfo' object has no attribute 'ip'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 59, in getPic
    oltInfo = OltInfo()
  File "/home/desarrollo/NetPics/OltInfo.py", line 26, in __init__
    Ip: {self.ip}
AttributeError: 'OltInfo' object has no attribute 'ip'
[31/05/2022 11:46:34 PM] root ERROR : 'OltInfo' object has no attribute 'ip'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 60, in getPic
    oltInfo = OltInfo()
  File "/home/desarrollo/NetPics/OltInfo.py", line 26, in __init__
    Ip: {self.ip}
AttributeError: 'OltInfo' object has no attribute 'ip'
[31/05/2022 11:47:11 PM] root ERROR : 'OltInfo' object has no attribute 'ip'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 60, in getPic
    oltInfo = OltInfo()
  File "/home/desarrollo/NetPics/OltInfo.py", line 26, in __init__
    Ip: {self.ip}
AttributeError: 'OltInfo' object has no attribute 'ip'
[31/05/2022 11:47:45 PM] root ERROR : 'OltInfo' object has no attribute 'ip'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 60, in getPic
    oltInfo = OltInfo()
  File "/home/desarrollo/NetPics/OltInfo.py", line 26, in __init__
    Ip: {self.ip}
AttributeError: 'OltInfo' object has no attribute 'ip'
[31/05/2022 11:49:37 PM] root ERROR : 'OltInfo' object has no attribute 'ip'
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 60, in getPic
    oltInfo = OltInfo()
  File "/home/desarrollo/NetPics/OltInfo.py", line 26, in __init__
    Ip: {self.ip}
AttributeError: 'OltInfo' object has no attribute 'ip'
[01/06/2022 12:01:34 AM] root ERROR : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM pics                         RIGHT' at line 1")
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 73, in getPic
    responseDb = self.db.selectOnusFromPicAndOlt(pic.id, olt.id)
  File "/home/desarrollo/NetPics/NetPixDB.py", line 151, in selectOnusFromPicAndOlt
    cur.execute("SELECT olt_info_id, onu_number, status, desc, rx, tx, sn \
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM pics                         RIGHT' at line 1")
[01/06/2022 12:01:34 AM] root ERROR : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM pics                         RIGHT' at line 1")
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 73, in getPic
    responseDb = self.db.selectOnusFromPicAndOlt(pic.id, olt.id)
  File "/home/desarrollo/NetPics/NetPixDB.py", line 151, in selectOnusFromPicAndOlt
    cur.execute("SELECT olt_info_id, onu_number, status, desc, rx, tx, sn \
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM pics                         RIGHT' at line 1")
[01/06/2022 12:04:24 AM] root ERROR : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM olt_info                         R' at line 1")
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 73, in getPic
    responseDb = self.db.selectOnusFromPicAndOlt(pic.id, olt.id)
  File "/home/desarrollo/NetPics/NetPixDB.py", line 151, in selectOnusFromPicAndOlt
    cur.execute("SELECT olt_info_id, onu_number, status, desc, rx, tx, sn \
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM olt_info                         R' at line 1")
[01/06/2022 12:04:24 AM] root ERROR : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM olt_info                         R' at line 1")
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 73, in getPic
    responseDb = self.db.selectOnusFromPicAndOlt(pic.id, olt.id)
  File "/home/desarrollo/NetPics/NetPixDB.py", line 151, in selectOnusFromPicAndOlt
    cur.execute("SELECT olt_info_id, onu_number, status, desc, rx, tx, sn \
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM olt_info                         R' at line 1")
[01/06/2022 12:05:54 AM] root ERROR : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM onu_info                         R' at line 1")
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 73, in getPic
    responseDb = self.db.selectOnusFromPicAndOlt(pic.id, olt.id)
  File "/home/desarrollo/NetPics/NetPixDB.py", line 151, in selectOnusFromPicAndOlt
    cur.execute("SELECT olt_info_id, onu_number, status, desc, rx, tx, sn \
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM onu_info                         R' at line 1")
[01/06/2022 12:05:54 AM] root ERROR : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM onu_info                         R' at line 1")
Traceback (most recent call last):
  File "/home/desarrollo/NetPics/main.py", line 73, in getPic
    responseDb = self.db.selectOnusFromPicAndOlt(pic.id, olt.id)
  File "/home/desarrollo/NetPics/NetPixDB.py", line 151, in selectOnusFromPicAndOlt
    cur.execute("SELECT olt_info_id, onu_number, status, desc, rx, tx, sn \
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'desc, rx, tx, sn                         FROM onu_info                         R' at line 1")
[01/06/2022 10:37:08 AM] root INFO : HUAWEI
[01/06/2022 10:37:09 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386944', 'value': '##OLT2-Cordoba_Mza_04/05/007-Caseros_690_(2)_Resi_gpon0/10/4##'}
[01/06/2022 10:37:14 AM] root INFO : HUAWEI
[01/06/2022 10:37:15 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386944', 'value': '##OLT2-Cordoba_Mza_04/05/007-Caseros_690_(2)_Resi_gpon0/10/4##'}
[01/06/2022 10:37:15 AM] root INFO : ZTE C300
[01/06/2022 10:37:16 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278724', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo748-gpon-olt_1/2/4##'}
[01/06/2022 10:37:18 AM] root INFO : ZTE C300
[01/06/2022 10:37:18 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278724', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo748-gpon-olt_1/2/4##'}
[01/06/2022 10:39:56 AM] root INFO : HUAWEI
[01/06/2022 10:39:56 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[01/06/2022 10:40:02 AM] root INFO : HUAWEI
[01/06/2022 10:40:03 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[01/06/2022 10:40:03 AM] root INFO : ZTE C300
[01/06/2022 10:40:03 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[01/06/2022 10:40:06 AM] root INFO : ZTE C300
[01/06/2022 10:40:16 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 03:29:46 PM] root INFO : HUAWEI
[02/06/2022 03:29:46 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 03:29:52 PM] root INFO : HUAWEI
[02/06/2022 03:29:52 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 03:29:53 PM] root INFO : ZTE C300
[02/06/2022 03:29:53 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 03:29:55 PM] root INFO : ZTE C300
[02/06/2022 03:29:55 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 03:30:56 PM] root INFO : HUAWEI
[02/06/2022 03:30:56 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 03:31:02 PM] root INFO : HUAWEI
[02/06/2022 03:31:02 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 03:31:03 PM] root INFO : ZTE C300
[02/06/2022 03:31:03 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 03:31:06 PM] root INFO : ZTE C300
[02/06/2022 03:31:06 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 03:31:38 PM] root INFO : HUAWEI
[02/06/2022 03:31:39 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 03:31:44 PM] root INFO : HUAWEI
[02/06/2022 03:31:44 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 03:31:45 PM] root INFO : ZTE C300
[02/06/2022 03:31:45 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 03:31:47 PM] root INFO : ZTE C300
[02/06/2022 03:31:47 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 03:31:47 PM] root INFO : Se tomó la foto Evento33
[02/06/2022 03:31:47 PM] root INFO : Se subió la foto Evento33
[02/06/2022 04:19:50 PM] root INFO : HUAWEI
[02/06/2022 04:19:51 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 04:19:56 PM] root INFO : HUAWEI
[02/06/2022 04:19:56 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 04:19:57 PM] root INFO : ZTE C300
[02/06/2022 04:19:57 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 04:19:59 PM] root INFO : ZTE C300
[02/06/2022 04:19:59 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 04:19:59 PM] root INFO : Se tomó la foto Volando
[02/06/2022 04:20:11 PM] root INFO : HUAWEI
[02/06/2022 04:20:12 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 04:20:17 PM] root INFO : HUAWEI
[02/06/2022 04:20:17 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 04:20:18 PM] root INFO : ZTE C300
[02/06/2022 04:20:18 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 04:20:22 PM] root INFO : ZTE C300
[02/06/2022 04:20:22 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 04:20:22 PM] root INFO : Se tomó la foto Volando
[02/06/2022 04:20:52 PM] root INFO : HUAWEI
[02/06/2022 04:20:52 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 04:20:58 PM] root INFO : HUAWEI
[02/06/2022 04:20:58 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 04:20:59 PM] root INFO : ZTE C300
[02/06/2022 04:20:59 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 04:21:01 PM] root INFO : ZTE C300
[02/06/2022 04:21:01 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 04:21:01 PM] root INFO : Se tomó la foto Volando
[02/06/2022 05:10:16 PM] root INFO : HUAWEI
[02/06/2022 05:10:17 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 05:10:23 PM] root INFO : HUAWEI
[02/06/2022 05:10:23 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 05:10:24 PM] root INFO : ZTE C300
[02/06/2022 05:10:24 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 05:10:27 PM] root INFO : ZTE C300
[02/06/2022 05:10:27 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 05:10:27 PM] root INFO : Se tomó la foto Evento34
[02/06/2022 05:10:27 PM] root INFO : Se subió la foto Evento34
[02/06/2022 05:13:11 PM] root INFO : HUAWEI
[02/06/2022 05:13:11 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 05:13:17 PM] root INFO : HUAWEI
[02/06/2022 05:13:17 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 05:13:18 PM] root INFO : ZTE C300
[02/06/2022 05:13:19 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 05:13:21 PM] root INFO : ZTE C300
[02/06/2022 05:13:21 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 05:13:21 PM] root INFO : Se tomó la foto Evento35
[02/06/2022 05:13:21 PM] root INFO : Se subió la foto Evento35
[02/06/2022 05:14:13 PM] root INFO : HUAWEI
[02/06/2022 05:14:13 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 05:14:19 PM] root INFO : HUAWEI
[02/06/2022 05:14:19 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[02/06/2022 05:14:20 PM] root INFO : ZTE C300
[02/06/2022 05:14:20 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 05:14:22 PM] root INFO : ZTE C300
[02/06/2022 05:14:22 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[02/06/2022 05:14:22 PM] root INFO : Se tomó la foto Volando
[07/06/2022 04:22:33 PM] root INFO : HUAWEI
[07/06/2022 04:22:34 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[07/06/2022 04:22:40 PM] root INFO : HUAWEI
[07/06/2022 04:22:40 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[07/06/2022 04:22:40 PM] root INFO : ZTE C300
[07/06/2022 04:22:41 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[07/06/2022 04:22:43 PM] root INFO : ZTE C300
[07/06/2022 04:22:43 PM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[07/06/2022 04:22:43 PM] root INFO : Se tomó la foto Evento35
[08/06/2022 10:29:38 AM] root INFO : HUAWEI
[08/06/2022 10:29:39 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[08/06/2022 10:29:45 AM] root INFO : HUAWEI
[08/06/2022 10:29:45 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[08/06/2022 10:29:45 AM] root INFO : ZTE C300
[08/06/2022 10:29:45 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[08/06/2022 10:29:48 AM] root INFO : ZTE C300
[08/06/2022 10:29:48 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[08/06/2022 10:29:48 AM] root INFO : Se tomó la foto Evento36
[08/06/2022 10:30:30 AM] root INFO : HUAWEI
[08/06/2022 10:30:31 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[08/06/2022 10:30:38 AM] root INFO : HUAWEI
[08/06/2022 10:30:38 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.31.1.1.1.18.4194386432', 'value': '##OLT2-Cordoba-Mza_79-04/09/035-H.Yrigoyen_433_(2)_Resi_gpon0/10'}
[08/06/2022 10:30:38 AM] root INFO : ZTE C300
[08/06/2022 10:30:38 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[08/06/2022 10:30:41 AM] root INFO : ZTE C300
[08/06/2022 10:30:41 AM] root INFO : <class 'SNMPResponse.SNMPResponse'>: {'ifIndex': '1.3.6.1.2.1.2.2.1.2.285278721', 'value': '##OLT_S-TELMO-01-Nodo_avdemayo605-gpon-olt_1/2/1##'}
[08/06/2022 10:30:41 AM] root INFO : Se tomó la foto Evento36
[08/06/2022 10:30:41 AM] root INFO : Se subió la foto Evento36
